import "./globals.css";

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Image from "next/image";

import Logo from "@/assets/logo.svg";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ignite Shop",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <div className="flex min-h-screen flex-col items-start justify-center">
          <header className="mx-auto w-full max-w-[1180px] py-8">
            <Image src={Logo.src} alt="Logo Ignite" />
          </header>
        </div>
        {children}
      </body>
    </html>
  );
}
